//=============================================================================
//
// file :        Rontec.h
//
// description : Include for the Rontec class.
//
// project :	RRontec
//
// $Author: tithub $
//
// $Revision: 1.2 $
//
// $Log: not supported by cvs2svn $
// Revision 1.1.1.1  2005/09/30 12:13:33  syldup
// initial import
//
// Revision 1.1  2005/09/09 15:38:21  coquet
// initial import, tested with real hardware.
// Raw version, a lot of functions are not implemented ( hard-coded ) but DS is usable
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================
#ifndef _RONTEC_H
#define _RONTEC_H

#include <Tango.h>
#include <DeviceProxyHelper.h>
#include "RontecImpl.h"

//using namespace Tango;

/**
 * @author	$Author: tithub $
 * @version $Revision: 1.2 $
 */

 //	Add your own constants definitions here.
 //-----------------------------------------------
#define NB_MAX_ROI 8

namespace Rontec_ns
{
/**
 * Class Description:
 * handles Rontec MCA channel analyser through a serail RS232 line
 */

/*
 *	Device States Description:
 *  Tango::STANDBY :  RONTEC OK, ready to accept command
 *
 *  Tango::RUNNING :  acquisition in progress
 *
 *  Tango::FAULT :    command error
 *
 *  Tango::UNKNOWN :  communication loosed with RONTEC
 *
 *  Tango::INIT :      */


class Rontec: public Tango::Device_3Impl
{
public :
	//	Add your own data members here
	//-----------------------------------------
	Tango::DevLong *attr_roi_read[NB_MAX_ROI];

	//	Here is the Start of the automatic code generation part
	//-------------------------------------------------------------	
/**
 *	@name attributes
 *	Attributs member data.
 */
//@{
		Tango::DevDouble	*attr_dataSpectrum_read;
		Tango::DevShort	*attr_nbChannels_read;
		Tango::DevShort	attr_nbChannels_write;
		Tango::DevDouble	*attr_integrationTime_read;
		Tango::DevDouble	attr_integrationTime_write;
		Tango::DevShort	*attr_timingType_read;
		Tango::DevShort	attr_timingType_write;
		Tango::DevString	*attr_dataSource_read;
		Tango::DevDouble	*attr_deadTime_read;
		Tango::DevDouble	*attr_countRate_read;
		Tango::DevDouble	*attr_realTime_read;
		Tango::DevDouble	*attr_liveTime_read;
		Tango::DevLong	*attr_roisStartsEnds_read;
		Tango::DevLong	*attr_roisStarts_read;
		Tango::DevLong	*attr_roisEnds_read;
		Tango::DevDouble	*attr_cycleTime_read;
		Tango::DevDouble	attr_cycleTime_write;
		Tango::DevShort	attr_startingChannel_write;
		Tango::DevShort	attr_endingChannel_write;
		Tango::DevDouble	*attr_detectorTemperature_read;
		Tango::DevLong	*attr_energyRange_read;
		Tango::DevLong	attr_energyRange_write;
		Tango::DevLong	*attr_offsetGain_read;
		Tango::DevBoolean	attr_readDataSpectrum_write;
//@}
		
/**
 *	@name Device properties
 *	Device properties member data.
 */
//@{
/**
 *	baud rate set on the RONTEC
 *	Default is 38400 ( firmware default )
 *	to set another baud rate :
 *	set on the RONTEC a new baudrate, write it on the flash,
 *	then update the property with the new value
 *	restart SerialLine the Rontec DServers
 *	possible values : 600, 1200, 1800, 2400, 3600, 4800, 7200, 9600, 14400,
 *	19200, 28800, 38400, 57600, 76800, 115200, 230400.
 */
	Tango::DevLong	baud;
/**
 *	Tango name of the serial line device
 *	the other serial line properties are fixed for the RONTEC RCL :
 *	N( no parity),8( data bits),1(stop bit), hardware handshake ( RTS/CTS
 */
	string	serialLineUrl;
/**
 *	list of the TTL outputs connected to a counter
 *	just for control and throw exception if try to configure a ROI that is not in the list
 *	8 TTL outputs are available with the current RONTEC MCA hardware
 *	example : 1 4 represents : ouptut1, output 4 connected
 *	default : 1
 */
	string	connectedROIMask;
/**
 *	number of channels of the MCA.
 *	The current RONTEC MCA hardware has 4096 channels.
 *	this is for extentions purpose only,
 *	let the default value of 4096
 */
	Tango::DevLong	numberOfChannels;
/**
 *	maximum fluo energy of the last MCA channel.
 *	with the current RONTEC MCA Hardware can be 10, 20, 40, or 80 KeV
 *	default : 80.0
 */
	Tango::DevDouble	maxFluoEnergy;
//@}

/**@name Constructors
 * Miscellaneous constructors */
//@{
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	Rontec(Tango::DeviceClass *cl,string &s);
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	Rontec(Tango::DeviceClass *cl,const char *s);
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device name
 *	@param d	Device description.
 */
	Rontec(Tango::DeviceClass *cl,const char *s,const char *d);
//@}

/**@name Destructor
 * Only one desctructor is defined for this class */
//@{
/**
 * The object desctructor.
 */	
	~Rontec() {delete_device();};
/**
 *	will be called at device destruction or at init command.
 */
	void delete_device();
//@}

	
/**@name Miscellaneous methods */
//@{
/**
 *	Initialize the device
 */
	virtual void init_device();
/**
 *	Always executed method befor execution command method.
 */
	virtual void always_executed_hook();

//@}

/**
 * @name Rontec methods prototypes
 */

//@{
/**
 *	Hardware acquisition for attributes.
 */
	virtual void read_attr_hardware(vector<long> &attr_list);
/**
 *	Extract real attribute values for dataSpectrum acquisition result.
 */
	virtual void read_dataSpectrum(Tango::Attribute &attr);
/**
 *	Extract real attribute values for nbChannels acquisition result.
 */
	virtual void read_nbChannels(Tango::Attribute &attr);
/**
 *	Write nbChannels attribute values to hardware.
 */
	virtual void write_nbChannels(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for integrationTime acquisition result.
 */
	virtual void read_integrationTime(Tango::Attribute &attr);
/**
 *	Write integrationTime attribute values to hardware.
 */
	virtual void write_integrationTime(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for timingType acquisition result.
 */
	virtual void read_timingType(Tango::Attribute &attr);
/**
 *	Write timingType attribute values to hardware.
 */
	virtual void write_timingType(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for dataSource acquisition result.
 */
	virtual void read_dataSource(Tango::Attribute &attr);
/**
 *	Extract real attribute values for deadTime acquisition result.
 */
	virtual void read_deadTime(Tango::Attribute &attr);
/**
 *	Extract real attribute values for countRate acquisition result.
 */
	virtual void read_countRate(Tango::Attribute &attr);
/**
 *	Extract real attribute values for realTime acquisition result.
 */
	virtual void read_realTime(Tango::Attribute &attr);
/**
 *	Extract real attribute values for liveTime acquisition result.
 */
	virtual void read_liveTime(Tango::Attribute &attr);
/**
 *	Extract real attribute values for roisStartsEnds acquisition result.
 */
	virtual void read_roisStartsEnds(Tango::Attribute &attr);
/**
 *	Extract real attribute values for roisStarts acquisition result.
 */
	virtual void read_roisStarts(Tango::Attribute &attr);
/**
 *	Extract real attribute values for roisEnds acquisition result.
 */
	virtual void read_roisEnds(Tango::Attribute &attr);
/**
 *	Extract real attribute values for cycleTime acquisition result.
 */
	virtual void read_cycleTime(Tango::Attribute &attr);
/**
 *	Write cycleTime attribute values to hardware.
 */
	virtual void write_cycleTime(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for startingChannel acquisition result.
 */
	virtual void read_startingChannel(Tango::Attribute &attr);
/**
 *	Write startingChannel attribute values to hardware.
 */
	virtual void write_startingChannel(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for endingChannel acquisition result.
 */
	virtual void read_endingChannel(Tango::Attribute &attr);
/**
 *	Write endingChannel attribute values to hardware.
 */
	virtual void write_endingChannel(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for detectorTemperature acquisition result.
 */
	virtual void read_detectorTemperature(Tango::Attribute &attr);
/**
 *	Extract real attribute values for energyRange acquisition result.
 */
	virtual void read_energyRange(Tango::Attribute &attr);
/**
 *	Write energyRange attribute values to hardware.
 */
	virtual void write_energyRange(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for offsetGain acquisition result.
 */
	virtual void read_offsetGain(Tango::Attribute &attr);
/**
 *	Extract real attribute values for readDataSpectrum acquisition result.
 */
	virtual void read_readDataSpectrum(Tango::Attribute &attr);
/**
 *	Write readDataSpectrum attribute values to hardware.
 */
	virtual void write_readDataSpectrum(Tango::WAttribute &attr);
/**
 *	Read/Write allowed for dataSpectrum attribute.
 */
	virtual bool is_dataSpectrum_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for nbChannels attribute.
 */
	virtual bool is_nbChannels_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for integrationTime attribute.
 */
	virtual bool is_integrationTime_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for timingType attribute.
 */
	virtual bool is_timingType_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for dataSource attribute.
 */
	virtual bool is_dataSource_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for deadTime attribute.
 */
	virtual bool is_deadTime_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for countRate attribute.
 */
	virtual bool is_countRate_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for realTime attribute.
 */
	virtual bool is_realTime_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for liveTime attribute.
 */
	virtual bool is_liveTime_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for roisStartsEnds attribute.
 */
	virtual bool is_roisStartsEnds_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for roisStarts attribute.
 */
	virtual bool is_roisStarts_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for roisEnds attribute.
 */
	virtual bool is_roisEnds_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for cycleTime attribute.
 */
	virtual bool is_cycleTime_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for startingChannel attribute.
 */
	virtual bool is_startingChannel_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for endingChannel attribute.
 */
	virtual bool is_endingChannel_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for detectorTemperature attribute.
 */
	virtual bool is_detectorTemperature_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for energyRange attribute.
 */
	virtual bool is_energyRange_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for offsetGain attribute.
 */
	virtual bool is_offsetGain_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for readDataSpectrum attribute.
 */
	virtual bool is_readDataSpectrum_allowed(Tango::AttReqType type);
/**
 *	Execution allowed for Abort command.
 */
	virtual bool is_Abort_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for Arm command.
 */
	virtual bool is_Arm_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for ClearData command.
 */
	virtual bool is_ClearData_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for GetPartOfSpectrum command.
 */
	virtual bool is_GetPartOfSpectrum_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for GetPauseStatus command.
 */
	virtual bool is_GetPauseStatus_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for GetSpeedAndResolutionConfiguration command.
 */
	virtual bool is_GetSpeedAndResolutionConfiguration_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for Reset command.
 */
	virtual bool is_Reset_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for SendRontecMessage command.
 */
	virtual bool is_SendRontecMessage_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for SetReadSize command.
 */
	virtual bool is_SetReadSize_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for SetROIs command.
 */
	virtual bool is_SetROIs_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for SetSingleROI command.
 */
	virtual bool is_SetSingleROI_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for SetSpeedAndResolutionConfiguration command.
 */
	virtual bool is_SetSpeedAndResolutionConfiguration_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for Start command.
 */
	virtual bool is_Start_allowed(const CORBA::Any &any);
/**
 * stops acquisition already running
 *	@exception DevFailed
 */
	void	abort();
/**
 * will Arm the MCA (ie prepare the MCA).
 *	@exception DevFailed
 */
	void	arm();
/**
 * clears the acquisition memory
 *	@exception DevFailed
 */
	void	clear_data();
/**
 * returns the data starting at argin[0] (exception if argin[0] < starting channel cofigured
 *	for argin[1] channel truncated if exceeds the end_channel configured
 *	@param	argin	[0]starting channel, [1] size of channel
 *	@return	the data 
 *	@exception DevFailed
 */
	Tango::DevVarLongArray	*get_part_of_spectrum(const Tango::DevVarLongArray *);
/**
 * returns PAUSE or RUNNING according to acquisition stopped or running
 *	@return	PAUSE/RUNNING
 *	@exception DevFailed
 */
	Tango::DevString	get_pause_status();
/**
 * returns the processor configured :
 *	0 : max cps 1 : ... cps 2 : ..... cps 3 : min cps
 *	@return	processor number actually selected
 *	@exception DevFailed
 */
	Tango::DevLong	get_speed_and_resolution_configuration();
/**
 * 
 *	@return	string returend by the rontec
 *	@exception DevFailed
 */
	Tango::DevString	reset();
/**
 * 
 *	@param	argin	the command and arguments to be sent
 *	@return	the rontec answer as string
 *	@exception DevFailed
 */
	Tango::DevString	send_rontec_message(Tango::DevString);
/**
 * for the readin thread ,
 *	the number of channels to read in 1 shoot on the RONTEC MCA.
 *	low number increases the speed of reading.
 *	@param	argin	size to read in 1 shoot
 *	@exception DevFailed
 */
	void	set_read_size(Tango::DevLong);
/**
 * Set the ROIs. the parameter is an array with values going by pair: tab[0]=126, tab[1]=238 -> first ROI starts from 126, ends to 238 tab[2]=1569,tab[3]=2368 -> second ROI starts from 1569, ends to 2368.
 *	@param	argin	starts and ends of the ROI. eg: tab[0]=126, tab[1]=238, tab[2]=1569,tab[3]=2368
 *	@exception DevFailed
 */
	void	set_rois(const Tango::DevVarLongArray *);
/**
 * configures the TTL output number for pulse output photons processed with
 *	low_channel < energy < high_channel
 *	the RONTEC waits for energy so we retreive energy in DServer from channel and MaxFluoEnergy
 *	channels are retreived according amplifier and energy calibration.
 *	not alowed if acquisition is running
 *	Exception if ROI number not in the ConnectedROIMask property
 *	@param	argin	[0] : TTL output number, [1] low channel, [2] high channel
 *	@exception DevFailed
 */
	void	set_single_roi(const Tango::DevVarLongArray *);
/**
 * selects the processor
 *	0 : max cps ...... 3 : min cps
 *	depends on real hardware
 *	exception if error
 *	@param	argin	the processor selected 0..3
 *	@exception DevFailed
 */
	void	set_speed_and_resolution_configuration(Tango::DevLong);
/**
 * starts a acquisition previously configured with attributes startingChannel, endingChannel, integrationTime
 *	for time given in integrationTime
 *	clears memory in the MCA if not done.
 *	for continuous acquisition : integrationTime=0
 *	@exception DevFailed
 */
	void	start();

/**
 *	Read the device properties from database
 */
	 void get_device_property();
//@}

	//	Here is the end of the automatic code generation part
	//-------------------------------------------------------------	

	// DYNAMIC ATTRIBUTES
	//--------------------
protected:
	void create_dynamic_attributes();
public:
	virtual void read_roi(Tango::Attribute &attr,long num_roi);
	virtual bool is_roi_allowed(Tango::AttReqType type,long num_roi);

protected :	
	//	Add your own data members here
	//-----------------------------------------
	// writes back the write part of attribute
	bool is_ROI_configured(long ttl_number);
	
	// Rontec MCA implementation class
	RontecImpl* _mca;

	float _integration_time;	// integration time used with start() command
	bool _live_time;			// false = integration time in real time, true = integration time in live time
	bool _start_reading_thread;
};

} // namespace

#endif	// _RONTEC_H
