static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Instrumentation/Rontec/src/RontecStateMachine.cpp,v 1.4 2007-02-14 08:40:27 tithub Exp $";
//+=============================================================================
//
// file :         RontecStateMachine.cpp
//
// description :  C++ source for the Rontec and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author: tithub $
//
// $Revision: 1.4 $
//
// $Log: not supported by cvs2svn $
// Revision 1.3  2006/08/31 15:51:11  tithub
// * Les temps sont exprimés en seconde au lieu de millisecondes
// * La commande GetPartOfSpectrum renvoie une partie du spectre lu si le thread est running, ou lit une partie du spectre sur le Rontec sinon
// * La commande ClearData arrête le thread de lecture
// * Attributs StartingChannel et EndingChannel mémorisés
//
// Revision 1.2  2006/07/24 14:48:18  tithub
// Nouvelle interface Tango
//
// Revision 1.1.1.1  2005/09/30 12:13:34  syldup
// initial import
//
// Revision 1.1  2005/09/09 15:38:21  coquet
// initial import, tested with real hardware.
// Raw version, a lot of functions are not implemented ( hard-coded ) but DS is usable
//
//
// copyleft : 		Synchrotron SOLEIL
//								L'Orme des Merisiers
//								Saint-Aubin - BP 48
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include "Rontec.h"
#include "RontecClass.h"

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Rontec_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_dataSpectrum_allowed
// 
// description : 	Read/Write allowed for dataSpectrum attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_dataSpectrum_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_nbChannels_allowed
// 
// description : 	Read/Write allowed for nbChannels attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_nbChannels_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_integrationTime_allowed
// 
// description : 	Read/Write allowed for integrationTime attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_integrationTime_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_timingType_allowed
// 
// description : 	Read/Write allowed for timingType attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_timingType_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_dataSource_allowed
// 
// description : 	Read/Write allowed for dataSource attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_dataSource_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_deadTime_allowed
// 
// description : 	Read/Write allowed for deadTime attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_deadTime_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_countRate_allowed
// 
// description : 	Read/Write allowed for countRate attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_countRate_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_realTime_allowed
// 
// description : 	Read/Write allowed for realTime attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_realTime_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_liveTime_allowed
// 
// description : 	Read/Write allowed for liveTime attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_liveTime_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roisStartsEnds_allowed
// 
// description : 	Read/Write allowed for roisStartsEnds attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roisStartsEnds_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roisStarts_allowed
// 
// description : 	Read/Write allowed for roisStarts attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roisStarts_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roisEnds_allowed
// 
// description : 	Read/Write allowed for roisEnds attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roisEnds_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_cycleTime_allowed
// 
// description : 	Read/Write allowed for cycleTime attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_cycleTime_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_detectorTemperature_allowed
// 
// description : 	Read/Write allowed for detectorTemperature attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_detectorTemperature_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_energyRange_allowed
// 
// description : 	Read/Write allowed for energyRange attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_energyRange_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_offsetGain_allowed
// 
// description : 	Read/Write allowed for offsetGain attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_offsetGain_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_readDataSpectrum_allowed
// 
// description : 	Read/Write allowed for readDataSpectrum attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_readDataSpectrum_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi1_allowed
// 
// description : 	Read/Write allowed for roi1 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi1_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi2_allowed
// 
// description : 	Read/Write allowed for roi2 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi2_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi3_allowed
// 
// description : 	Read/Write allowed for roi3 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi3_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi4_allowed
// 
// description : 	Read/Write allowed for roi4 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi4_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi5_allowed
// 
// description : 	Read/Write allowed for roi5 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi5_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi6_allowed
// 
// description : 	Read/Write allowed for roi6 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi6_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi7_allowed
// 
// description : 	Read/Write allowed for roi7 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi7_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_roi8_allowed
// 
// description : 	Read/Write allowed for roi8 attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_roi8_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_spectrumEndValue_allowed
// 
// description : 	Read/Write allowed for spectrumEndValue attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_spectrumEndValue_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_spectrumStartValue_allowed
// 
// description : 	Read/Write allowed for spectrumStartValue attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_spectrumStartValue_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_energySpectrum_allowed
// 
// description : 	Read/Write allowed for energySpectrum attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_energySpectrum_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Abort_allowed
// 
// description : 	Execution allowed for Abort command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Abort_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Arm_allowed
// 
// description : 	Execution allowed for Arm command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Arm_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_ClearData_allowed
// 
// description : 	Execution allowed for ClearData command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_ClearData_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetPartOfSpectrum_allowed
// 
// description : 	Execution allowed for GetPartOfSpectrum command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetPartOfSpectrum_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetPauseStatus_allowed
// 
// description : 	Execution allowed for GetPauseStatus command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetPauseStatus_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetSpeedAndResolutionConfiguration_allowed
// 
// description : 	Execution allowed for GetSpeedAndResolutionConfiguration command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetSpeedAndResolutionConfiguration_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Reset_allowed
// 
// description : 	Execution allowed for Reset command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Reset_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SendRontecMessage_allowed
// 
// description : 	Execution allowed for SendRontecMessage command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SendRontecMessage_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetROIs_allowed
// 
// description : 	Execution allowed for SetROIs command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetROIs_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetSingleROI_allowed
// 
// description : 	Execution allowed for SetSingleROI command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetSingleROI_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetSpeedAndResolutionConfiguration_allowed
// 
// description : 	Execution allowed for SetSpeedAndResolutionConfiguration command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetSpeedAndResolutionConfiguration_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Start_allowed
// 
// description : 	Execution allowed for Start command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Start_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::UNKNOWN	||
		get_state() == Tango::INIT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

}	// namespace Rontec_ns
