static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Instrumentation/Rontec/src/RontecStateMachine.cpp,v 1.1.1.1 2005-09-30 12:13:34 syldup Exp $";
//+=============================================================================
//
// file : 				RontecStateMachine.cpp
//
// description :	C++ source for the Rontec and its alowed. 
//								method for commands and attributes
//
// project :			TANGO Device Server
//
// $Author: syldup $
//
// $Revision: 1.1.1.1 $
//
// $Log: not supported by cvs2svn $
// Revision 1.1  2005/09/09 15:38:21  coquet
// initial import, tested with real hardware.
// Raw version, a lot of functions are not implemented ( hard-coded ) but DS is usable
//
//
// copyleft : 		Synchrotron SOLEIL
//								L'Orme des Merisiers
//								Saint-Aubin - BP 48
//
//-=============================================================================
//
//			This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//				 (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <Rontec.h>
#include <RontecClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Rontec_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_fluoSpectrum_allowed
//
// description :	Read/Write allowed for fluoSpectrum attribute.
//
//-----------------------------------------------------------------------------
bool Rontec::is_fluoSpectrum_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetAcquisitionTime_allowed
//
// description :	Execution allowed for GetAcquisitionTime command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetAcquisitionTime_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::RUNNING ||
		get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetReadSize_allowed
//
// description :	Execution allowed for SetReadSize command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetReadSize_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::RUNNING ||
		get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Start_allowed
//
// description :	Execution allowed for Start command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Start_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::RUNNING ||
		get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Stop_allowed
// 
// description :	Execution allowed for Stop command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Stop_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetStartingChannel_allowed
// 
// description :	Execution allowed for SetStartingChannel command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetStartingChannel_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetEndingChannel_allowed
// 
// description :	Execution allowed for SetEndingChannel command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetEndingChannel_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetSpectrumLimits_allowed
//
// description :	Execution allowed for GetSpectrumLimits command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetSpectrumLimits_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetPartOfSpectrum_allowed
//
// description :	Execution allowed for GetPartOfSpectrum command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetPartOfSpectrum_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetSpeedAndResolutionConfiguration_allowed
//
// description :	Execution allowed for GetSpeedAndResolutionConfiguration command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetSpeedAndResolutionConfiguration_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetSpeedAndResolutionConfiguration_allowed
//
// description :	Execution allowed for SetSpeedAndResolutionConfiguration command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetSpeedAndResolutionConfiguration_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetRemainingAcquisitionTime_allowed
// 
// description :	Execution allowed for GetRemainingAcquisitionTime command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetRemainingAcquisitionTime_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetROIParameters_allowed
// 
// description :	Execution allowed for SetROIParameters command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetROIParameters_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetROIParameters_allowed
// 
// description :	Execution allowed for GetROIParameters command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetROIParameters_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Reset_allowed
//
// description :	Execution allowed for Reset command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Reset_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_InitSerialLine_allowed
//
// description :	Execution allowed for InitSerialLine command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_InitSerialLine_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_Clear_allowed
//
// description :	 Execution allowed for Clear command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_Clear_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetCycleTime_allowed
//
// description :	 Execution allowed for GetCycleTime command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetCycleTime_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetDeadTime_allowed
//
// description :	 Execution allowed for GetDeadTime command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetDeadTime_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetOutputCountRate_allowed
//
// description :	 Execution allowed for GetOutputCountRate command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetOutputCountRate_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetInputCountRate_allowed
//
// description :	 Execution allowed for GetInputCountRate command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetInputCountRate_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetDetectorTemperature_allowed
//
// description :	 Execution allowed for GetDetectorTemperature command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetDetectorTemperature_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetRoiCount_allowed
//
// description :	 Execution allowed for GetRoiCounte command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetRoiCount_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetEnergyRange_allowed
//
// description :	 Execution allowed for GetRoiCounte command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetEnergyRange_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SetEnergyRange_allowed
//
// description :	 Execution allowed for GetRoiCounte command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SetEnergyRange_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetOffsetGain_allowed
//
// description :	 Execution allowed for GetRoiCount command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetOffsetGain_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_GetPauseStatus_allowed
//
// description :	 Execution allowed for GetRoiCount command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_GetPauseStatus_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Rontec::is_SendRontecMessage_allowed
//
// description :	 Execution allowed for SendRontecMessage command.
//
//-----------------------------------------------------------------------------
bool Rontec::is_SendRontecMessage_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::UNKNOWN)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

} // namespace Rontec
